# Fish variables
# Generated by 'wal'
set wallpaper "{wallpaper}"

# Special
set background '{background}'
set foreground '{foreground}'
set cursor '{cursor}'

# Colors
set color0 '{color0}'
set color1 '{color1}'
set color2 '{color2}'
set color3 '{color3}'
set color4 '{color4}'
set color5 '{color5}'
set color6 '{color6}'
set color7 '{color7}'
set color8 '{color8}'
set color9 '{color9}'
set color10 '{color10}'
set color11 '{color11}'
set color12 '{color12}'
set color13 '{color13}'
set color14 '{color14}'
set color15 '{color15}'

# Shell colors
set fish_color_normal normal
set fish_color_command {color1.strip}
set fish_color_param {color5.strip}
set fish_color_redirection $fish_color_param
set fish_color_comment {color8.strip}
set fish_color_error ff0000
set fish_color_escape {color5.strip}
set fish_color_operator $fish_color_escape
set fish_color_end {color2.strip}
set fish_color_quote {color2.strip}
set fish_color_autosuggestion 555 brblack
set fish_color_user brgreen
set fish_color_host $fish_color_normal
set fish_color_valid_path --underline
set fish_color_cwd green
set fish_color_cwd_root red
set fish_color_match --background=brblue
set fish_color_search_match bryellow --background=brblack
set fish_color_selection white --bold --background=brblack
set fish_color_cancel -r
set fish_pager_color_prefix white --bold --underline
set fish_pager_color_completion
set fish_pager_color_description $fish_color_quote yellow
set fish_pager_color_progress brwhite --background=cyan
set fish_color_history_current --bold

# FZF colors
set -gx FZF_DEFAULT_OPTS "
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
